import logging

logger = logging.getLogger()

PYTHONPATH = $PYTHONPATH

RATELIMIT_STORAGE_URI = $SUPERSET_CACHE_REDIS_URL
SQLALCHEMY_DATABASE_URI = $SQLALCHEMY_DATABASE_URI
SUPERSET_CACHE_REDIS_URL = $SUPERSET_CACHE_REDIS_URL

CACHE_CONFIG = {
    "CACHE_TYPE": "RedisCache",
    "CACHE_DEFAULT_TIMEOUT": 300,
    "CACHE_KEY_PREFIX": "superset_",
    "CACHE_REDIS_HOST": $REDIS_HOST,
    "CACHE_REDIS_PORT": $REDIS_PORT,
    "CACHE_REDIS_DB": 0,
    'CACHE_REDIS_URL': $REDIS_URL 
}
DATA_CACHE_CONFIG = CACHE_CONFIG

class CeleryConfig(object):
    BROKER_URL = f$SUPERSET_CACHE_REDIS_URL + "/1"
    CELERY_IMPORTS= ("superset.sql_lab",)
    CELERY_RESULT_BACKEND = f$SUPERSET_CACHE_REDIS_URL + "/0"
    CELERY_ANNOTATIONS = {'tasks.add': {'rate_limit': '10/s'}}

CELERY_CONFIG = CeleryConfig

REDIS_HOST = $REDIS_HOST
REDIS_PORT = $REDIS_PORT

SUPERSET_ENV = $SUPERSET_ENV
SUPERSET_LOAD_EXAMPLES = $SUPERSET_LOAD_EXAMPLES
SUPERSET_SECRET_KEY = $SUPERSET_SECRET_KEY
SUPERSET_PORT = $SUPERSET_PORT